name: modulohu_web
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  bcrypt: ^1.1.3
  brasil_fields: ^1.15.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  dropdown_search: ^5.0.6
  easy_dynamic_theme: ^2.3.1
  file_picker: ^10.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^6.0.0
  flutter_html: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  go_router: ^16.2.1
  google_fonts: ^4.0.4
  http: ^0.13.3
  http_interceptor: ^1.0.2
  import_sorter: ^4.6.0
  intl: ^0.20.2
  logger: ^2.5.0
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.2
  web: ^1.1.1
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
